# Generated by Django 3.1.5 on 2021-02-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210204_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_supplier',
        ),
        migrations.AddField(
            model_name='user',
            name='is_supplier',
            field=models.BooleanField(default=False),
        ),
    ]
