# Generated by Django 3.1.5 on 2021-02-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210219_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='product',
            field=models.ManyToManyField(related_name='tag', to='product.Product'),
        ),
    ]
