# Generated by Django 3.1.5 on 2021-02-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210219_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='product',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
