# Generated by Django 3.1.5 on 2021-02-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210219_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='product',
            field=models.ManyToManyField(related_name='tags', to='product.Product'),
        ),
    ]
